Repository CapstoneDesign24-GQ/FE, pull requests merged in 2024-05, with the labels that each got.

#1 setting:react랑 라이브러리 설치 / global css 설정 중..props 오류남
  cd-gq/.gitignore
  cd-gq/README.md
  cd-gq/package-lock.json
  cd-gq/package.json
  cd-gq/public/favicon.ico
  cd-gq/public/index.html
  cd-gq/public/logo.png
  cd-gq/public/logo192.png
  cd-gq/public/logo512.png
  cd-gq/public/manifest.json
  cd-gq/public/robots.txt
  cd-gq/src/App.css
  cd-gq/src/App.js
  cd-gq/src/index.css
  cd-gq/src/index.js
  cd-gq/src/pages/main.js
  cd-gq/src/reportWebVitals.js
  cd-gq/src/setupTests.js
  cd-gq/src/styles/global.js
  cd-gq/src/styles/theme.js
  desktop.ini
Labels: ⚙ Setting

#3 docs: pr 템플릿 세팅
  cd-gq/.github/pull_request_template.md
Labels: 📃Docs

#8 setting:Global 설정 완료 / Global.js와 Mobile.js
  cd-gq/src/App.js
  cd-gq/src/index.js
  cd-gq/src/styles/Mobile.js
Labels: ⚙ Setting, 🎨 Html&Css

#9 feat: main페이지 구현
  cd-gq/src/App.js
  cd-gq/src/assets/images/LogoImg.png
  cd-gq/src/components/InputCrop.js
  cd-gq/src/components/InputDay.js
  cd-gq/src/components/InputLocation.js
  cd-gq/src/index.js
  cd-gq/src/pages/main.js
  cd-gq/src/styles/Mobile.js
Labels: 🎨 Html&Css

#13 feat/docs: mobile.js 설정하여 ui 크기 설정 완료
  cd-gq/src/App.js
  cd-gq/src/index.js
  cd-gq/src/pages/Sitemap.js
  cd-gq/src/pages/main.js
  cd-gq/src/styles/Mobile.js
Labels: ✨ Feature, 📃Docs

#14 docs/feat:InputLocation.js 완성.
  cd-gq/src/components/InputLocation.js
  cd-gq/src/pages/main.js
  cd-gq/src/styles/Mobile.js
  cd-gq/src/styles/global.js
  cd-gq/src/styles/theme.js
Labels: ✨ Feature, 🎨 Html&Css

#19 feat: main.js 에서 height가 컴포넌트 변경되며 백그라운드가 짤리는 현상 해결
  cd-gq/src/components/InputCrop.js
  cd-gq/src/components/InputDate.js
  cd-gq/src/components/InputLocation.js
  cd-gq/src/pages/main.js
Labels: ⚠️ BugFIx, ✨ Feature, 🎨 Html&Css

#20 feat: Detail페이지 백그라운드 구현
  cd-gq/src/assets/images/InsectTestImg.png
  cd-gq/src/assets/images/wormLeftTop.png
  cd-gq/src/assets/images/wormRightBottom.png
  cd-gq/src/components/DealWithPest.js
  cd-gq/src/components/PestInformation.js
  cd-gq/src/pages/Detail.js
  cd-gq/src/pages/Home.js
  cd-gq/src/pages/main.js
Labels: 💻 All

#21 design:DealWithPest.js component 작업 중. onToggle function error
  cd-gq/src/components/DealWithPest.js
  cd-gq/src/components/InputCrop.js
  cd-gq/src/components/InputDate.js
  cd-gq/src/components/InputLocation.js
  cd-gq/src/components/PestContent.js
  cd-gq/src/pages/Detail.js
  cd-gq/src/styles/theme.js
Labels: 🎨 Html&Css

#22 design:State.js Component ui 완성
  cd-gq/src/assets/images/wormRightTop.png
  cd-gq/src/components/DealWithPest.js
  cd-gq/src/components/State.js
  cd-gq/src/pages/Test1.js
  cd-gq/src/styles/theme.js
Labels: 🎨 Html&Css

#24 feat: Header.js Component ui 및 기능 구현
  cd-gq/src/components/Header.js
  cd-gq/src/pages/Home.js
Labels: 💻 All

#25 design:State.js Components width, height에 맞춰 다시 정렬
  cd-gq/src/components/InputDate.js
  cd-gq/src/components/State.js
  cd-gq/src/components/TestDate.js
  cd-gq/src/pages/Home.js
Labels: 🎨 Html&Css

#27 Hyunah1
  cd-gq/src/assets/images/cloud.png
  cd-gq/src/assets/images/wormRightTop.png
  cd-gq/src/components/Header.js
  cd-gq/src/components/Weather.js
  cd-gq/src/pages/Home.js
Labels: 🎨 Html&Css

#28 feat:dealWithPest.js toggle component 설정 후 중간 commit
  cd-gq/package-lock.json
  cd-gq/package.json
  cd-gq/src/components/Date.js
  cd-gq/src/components/DealWithPest.js
  cd-gq/src/components/InputDate.js
  cd-gq/src/components/ReactDatepicker.js
  cd-gq/src/components/TestDate.js
  cd-gq/src/styles/theme.js
Labels: 💻 All

#29 feat/design:dealWithPest.js 의 toggleComponent ui 완성
  cd-gq/src/components/DealWithPest.js
  cd-gq/src/components/InputDate.js
  cd-gq/src/components/PestContent.js
  cd-gq/src/styles/theme.js
Labels: 💻 All

#30 feat:Main page localStorage code inputDate 빼고 연동 완료
  cd-gq/src/components/InputCrop.js
  cd-gq/src/components/InputLocation.js
  cd-gq/src/components/State.js
  cd-gq/src/pages/main.js
Labels: 📬 API, ✨ Feature, ✅ Test

#31 feat: PestInformation.js 컴포넌트 구현
  cd-gq/src/assets/images/pestTestImg1.png
  cd-gq/src/components/DealWithPest.js
  cd-gq/src/components/PestInformation.js
  cd-gq/src/db/PestInfo.json
  cd-gq/src/pages/Detail.js
Labels: 📬 API, 💻 All

#33 feat(InputDate) : InputDate.js component Main.js의 inputData에 저장하기 성공
  cd-gq/README.md
  cd-gq/package-lock.json
  cd-gq/package.json
  cd-gq/src/components/DealWithPest.js
  cd-gq/src/components/InputDate.js
  cd-gq/src/components/TestDate.js
  cd-gq/src/components/TextDate02.js
  cd-gq/src/pages/main.js
Labels: 📬 API, 💻 All

#35 feat: Weather.js 컴포넌트에 기상청 API연동 완료
  cd-gq/.gitignore
  cd-gq/package-lock.json
  cd-gq/package.json
  cd-gq/src/components/Weather.js
Labels: 📬 API, 💻 All

#37 setting : root dr
  .gitignore
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo.png
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/assets/images/InsectTestImg.png
  src/assets/images/LogoImg.png
  src/assets/images/cloud.png
  src/assets/images/pestTestImg1.png
  src/assets/images/wormLeftTop.png
  src/assets/images/wormRightBottom.png
  src/assets/images/wormRightTop.png
  src/components/BlockButton.js
  src/components/Date.js
  src/components/DatePicker.js
  src/components/DealWithPest.js
  src/components/Header.js
  src/components/InputCrop.js
  src/components/InputDate.js
  src/components/InputLocation.js
  src/components/PestInformation.js
  src/components/ReactDatepicker.js
  src/components/State.js
  src/components/Weather.js
  src/db/PestInfo.json
  src/index.css
  src/index.js
  src/pages/Detail.js
  src/pages/Home.js
  src/pages/Sitemap.js
  src/pages/Test1.js
  src/pages/main.js
  src/reportWebVitals.js
  src/routes.js
  src/setupTests.js
  src/styles/Mobile.js
  src/styles/global.js
  src/styles/theme.js
Labels: ⚙ Setting, 🌏 Deploy

#38 setting(Vercel)
  package-lock.json
  package.json
Labels: ⚙ Setting, 🌏 Deploy
